import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Pre-existing findings surfaced by the migration to flat config. They are
    // reported as warnings so `npm run lint` passes while they stay visible.
    // The react-hooks rules come from the React Compiler ruleset (eslint-plugin-
    // react-hooks v7); this project does not enable the compiler. Promote each
    // rule back to "error" once its occurrences are fixed.
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
      "react-hooks/immutability": "warn",
      "react-hooks/preserve-manual-memoization": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/set-state-in-effect": "warn",
    },
  },
  globalIgnores([
    ".next/**",
    ".open-next/**",
    ".sst/**",
    ".claude/**",
    "out/**",
    "next-env.d.ts",
    // Generated by SST; excluded from tsconfig too and relies on a
    // triple-slash reference into the untracked .sst directory.
    "sst.config.ts",
  ]),
]);
